const scene=new THREE.Scene();scene.background=new THREE.Color(0x080b0e);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,.1,8.8);
const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#scene'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
scene.add(new THREE.AmbientLight(0x7c7b78,.65));const key=new THREE.DirectionalLight(0xd7bf91,2.4);key.position.set(-3,5,5);scene.add(key);const rim=new THREE.PointLight(0x63727a,2,14);rim.position.set(4,-1,4);scene.add(rim);
const paperMat=new THREE.MeshStandardMaterial({color:0xc5ad82,roughness:.92});const paper=new THREE.Mesh(new THREE.PlaneGeometry(6.8,3.9,120,40),paperMat);paper.rotation.x=-.06;scene.add(paper);
function roll(x){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x49351f,roughness:.7});const rod=new THREE.Mesh(new THREE.CylinderGeometry(.17,.17,4.15,32),mat);rod.rotation.z=Math.PI/2;g.add(rod);for(const px of[-2.1,2.1]){const cap=new THREE.Mesh(new THREE.SphereGeometry(.23,24,16),mat);cap.position.x=px;g.add(cap)}g.position.x=x;scene.add(g);return g}
const left=roll(-3.55),right=roll(3.55);const curlMat=new THREE.MeshStandardMaterial({color:0xa78d60,roughness:1});
const curls=[];for(const x of[-3.45,3.45]){const c=new THREE.Mesh(new THREE.CylinderGeometry(.43,.43,4.0,48),curlMat);c.rotation.z=Math.PI/2;c.position.x=x;scene.add(c);curls.push(c)}
const marks=new THREE.Group();const ink=new THREE.MeshStandardMaterial({color:0x4a3b29,roughness:1});for(let i=0;i<32;i++){const w=.12+Math.random()*.5;const m=new THREE.Mesh(new THREE.BoxGeometry(w,.018,.018),ink);m.position.set(-2.7+Math.random()*5.4,-1.2+Math.random()*2.4,.05);m.rotation.z=(Math.random()-.5)*.12;marks.add(m)}paper.add(marks);
const particles=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xbca87f,size:.025,transparent:true,opacity:.45}));const pos=[];for(let i=0;i<280;i++)pos.push((Math.random()-.5)*15,(Math.random()-.5)*8,Math.random()*-5);particles.geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));scene.add(particles);
let progress=0,target=0;const clamp=v=>Math.max(0,Math.min(1,v));
function openScroll(){target=1;document.body.classList.add('opened')}
document.querySelector('#open').addEventListener('click',openScroll);document.querySelector('#enter').addEventListener('click',()=>document.querySelector('#method').scrollIntoView({behavior:'smooth'}));
addEventListener('wheel',e=>{if(scrollY<innerHeight*1.15)target=clamp(target+e.deltaY*.0009)},{passive:true});
addEventListener('mousemove',e=>{camera.position.x+=(e.clientX/innerWidth-.5)*.65-camera.position.x*.035;camera.position.y+=(.5-e.clientY/innerHeight)*.3-camera.position.y*.035});
function animate(){requestAnimationFrame(animate);progress+=(target-progress)*.055;const p=progress;const spread=3.45*p;left.position.x=-spread;right.position.x=spread;left.rotation.y=-p*.9;right.rotation.y=p*.9;paper.scale.x=.08+.92*p;paper.position.z=-.2+.2*p;paper.position.y=-.15+.15*p;for(const c of curls)c.scale.set(.8+.2*p,1,1);marks.rotation.y=.12*p;camera.position.z=8.8-1.2*p;camera.lookAt(0,0,0);particles.rotation.y+=.00015;renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
